### ISSUE TITLE
Can not start KISS GUI on Mac OS Mojave 10.14.3

### ISSUE THREAD

**Issue by Richygoat** [fedorcomander/kiss-gui#12] opened 2019-09-15 20:08 UTC
I tried to install the new GUI but every time i want to start the program it shows a message that the program is broken. Options are move in trash or cancel.

KISS GUI 2.0.13 worked before.

**Comment by lichtl** [comment] 2019-09-16 21:24
this is related to MacOS because the app is not signed with an apple certificate. 

I'm currently try to resolve it. Could you test if this one works?
** removed link since it wasn't working properly**

**Comment by schm00tzig** [comment] 2019-10-09 18:36
any news on this?
2.0.15 works fine. 2.0.16 doesn't

**Comment by lichtl** [comment] 2019-10-09 19:34
There is currently a zip file with only the app (this has been tested and confirmed to work) you might have to right-click->open on first attempt

**Comment by aee74** [comment] 2019-10-17 15:01
I Have the same issue, tried the https://medium.com/@panayiotisgeorgiou/how-to-fix-damaged-app-message-on-macos-sierra-f11dbf683e7a but this does not work Also tried downloading the zip and control open the file. same issue. I'm on Mac OS Catalina

**Comment by GSGC** [comment] 2019-10-20 08:42
This worked for me, just drop the downloaded zip folder into "Applications" then follow these instructions. just change the source folder from "betaflight to match the Kiss FC location **"Changes to the security model used in the latest versions of MacOS X 10.14 (Mojave) and 10.15 (Catalina) mean that the operating system will show an error message ('"Betaflight Configurator.app" is damaged and can’t be opened. You should move it to the Trash.') when trying to install the application. To work around this, ruthe following command in a terminal before installing:** sudo xattr -rd com.apple.quarantine /Applications/Betaflight\ Configurator.app;

**Comment by aee74** [comment] 2019-10-20 10:54
Found this YT link. https://youtu.be/6fqzb4qpgcs
Works great

**Comment by lichtl** [comment] 2019-11-08 16:35
should also be resolved with the latest GUI

**Closed as completed by lichtl** 2019-11-08 16:35 UTC
